services:
  # Database
  db:
    image: mysql:9.1.0
    volumes: 
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: LSsuT-.57f8_6Ch,
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: r9hpq*!H!ko$L@hjg6
    networks:
      - wpsite
  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin:5.2.1
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: LSsuT-.57f8_6Ch,
    networks:
      - wpsite
  # Wordpress
  wordpress:
    depends_on:
      - db
    image: wordpress:php8.3
    volumes: ["./:/var/www/html"]
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: r9hpq*!H!ko$L@hjg6
    ports:
      - "8080:80"
    networks: 
      - wpsite
networks:
  wpsite:
volumes:
  db_data:
